import pandas as pd
import psycopg2
from sqlalchemy import create_engine

data = {
    "Misiones": {
        "Municipios": [
            "Posadas",
            "Apóstoles",
            "Tres Capones",
            "Mártires",
            "Santiago de Liniers",
            "San Pedro",
            "Campo Grande",
            "Puerto Rico",
            "Montecarlo",
            "El Soberbio",
            "Cerro Corá",
            "Garupá",
            "Santa Ana",
            "Corpus",
            "Gobernador Roca",
            "Panambí",
            "Hipólito Irigoyen",
            "Profundidad",
            "Azara",
            "Colonia Aurora",
            "Fachinal",
            "El Alcázar",
            "Capioví",
            "Santo Pipo",
            "Colonia Polana",
            "Gobernador López",
            "Jardín América",
            "Caa Yarí",
            "Olegario V. Andrade",
            "Cerro Azul",
            "General J. J. Urquiza",
            "Alba Posse",
            "Los Helechos",
            "San Vicente",
            "Mojón Grande",
            "Gral. Alvear",
            "San Javier",
            "Ruiz de Montoya",
            "Santa María",
            "Guaraní",
            "San Martín",
            "San José",
            "Puerto Esperanza",
            "Itacaruaré",
            "Almafuerte",
            "Colonia Alberdi",
            "Leandro N. Alem",
            "Colonia Delicia",
            "Bernardo de Irigoyen",
            "Colonia Victoria",
            "25 de Mayo",
            "Oberá",
            "Iguazú",
            "Leoni",
            "Caraguatay",
            "Campo Viera",
            "Dos Arroyos",
            "Concepción de la Sierra",
            "Arroyo del Medio",
            "9 de Julio",
            "Bonpland",
            "San Ignacio",
            "Comandante A. Guacurary",
            "San Antonio",
            "Aristóbulo del Valle",
            "Ameghino",
            "Campo Ramón",
            "Eldorado",
            "Puerto Piray",
            "Garuhapé",
            "Colonia Wanda",
            "Dos de Mayo",
            "Candelaria",
            "Loreto",
            "Libertad"
        ],
        "ISO": "AR-N"
    },
    "San Luis": {
        "Municipios": [
            "San Luis",
            "Zanjitas",
            "Beazley",
            "Balde",
            "Fraga",
            "P. de los Funes",
            "Carolina",
            "San Francisco",
            "Merlo",
            "Juana Koslay",
            "Batavia",
            "Ranqueles",
            "Alto Pencoso",
            "Las Aguadas",
            "San Martin",
            "Leandro N. Alem",
            "La Calera",
            "La Punilla",
            "Fortin el Patria",
            "Lujan",
            "Quines",
            "Las Vertientes",
            "Paso Grande",
            "El Trapiche",
            "Navia",
            "Desaguadero",
            "Villa Mercedes",
            "Candelaria",
            "Alto Pelado",
            "Las Lagunas",
            "Las Chacras",
            "V, de Praga",
            "Villa del Carmen",
            "San Pablo",
            "Renca",
            "Tilisarao",
            "Los Molles",
            "V, Gral, Roca",
            "V, de la Quebrada",
            "Nogoli",
            "Carpinteria",
            "La Toma",
            "Juan Llerena",
            "Concaran",
            "Talita",
            "Sta Rosa del Conlara",
            "Villa Larca",
            "Papagayos",
            "Naschel",
            "Justo Daract",
            "Saladillo",
            "Bagual",
            "Arizona",
            "Buena Esperanza",
            "Union",
            "San Jeronimo",
            "El Volcan",
            "Estancia Grande",
            "La Punta",
            "Nueva Galia",
            "Fortuna",
            "Anchorena",
            "Juan Jorba",
            "Lavaisse",
            "San Jose del Morro",
            "Cortaderas",
            "Lafinur"
        ],
        "ISO": "AR-D"
    },
    "San Juan": {
        "Municipios": [
            "San Juan",
            "Iglesia",
            "Valle Fértil",
            "Ullum",
            "Albardón",
            "Zonda",
            "Chimbas",
            "Rivadavia",
            "Santa Lucía",
            "Rawson",
            "Pocito",
            "Sarmiento",
            "Jáchal",
            "Calingasta",
            "25 de Mayo",
            "9 de Julio",
            "San Martín",
            "Angaco",
            "Caucete"
        ],
        "ISO": "AR-J"
    },
    "Entre Ríos": {
        "Municipios": [
            "Paraná",
            "Aldea Brasilera",
            "Aldea María Luisa",
            "Aldea San Antonio",
            "Aranguren",
            "Basavilbaso",
            "Bovril",
            "Caseros",
            "Ceibas",
            "Cerrito",
            "Chajarí",
            "Colonia Avellaneda",
            "Colonia Ayuí",
            "Colonia Elía",
            "Colón",
            "Concepción del Uruguay",
            "Concordia",
            "Conscripto Bernardi",
            "Crespo",
            "Diamante",
            "El Pingo",
            "Enrique Carbó",
            "Estancia Grande",
            "Federación",
            "Federal",
            "General Campos",
            "General Galarza",
            "General Ramírez",
            "Gilbert",
            "Gobernador Maciá",
            "Gobernador Mansilla",
            "Gualeguay",
            "Gualeguaychú",
            "Hasenkamp",
            "Hernández",
            "Herrera",
            "Ibicuy",
            "La Criolla",
            "La Paz",
            "Larroque",
            "Libertador San Martín",
            "Los Charrúas",
            "Los Conquistadores",
            "Lucas González",
            "María Grande",
            "Nogoyá",
            "Oro Verde",
            "Piedras Blancas",
            "Primero de Mayo",
            "Pronunciamiento",
            "Pueblo Brugo",
            "Pueblo General Belgrano",
            "Pueblo Liebig",
            "Puerto Yeruá",
            "Rosario del Tala",
            "San Benito",
            "San Gustavo",
            "San Jaime de la Frontera",
            "San José",
            "San José de Feliciano",
            "San Justo",
            "San Salvador",
            "Santa Ana",
            "Santa Anita",
            "Santa Elena",
            "Sauce de Luna",
            "Seguí",
            "Tabossi",
            "Ubajay",
            "Urdinarrain",
            "Valle María",
            "Viale",
            "Victoria",
            "Villa Alcaraz",
            "Villa Clara",
            "Villa del Rosario",
            "Villa Domínguez",
            "Villa Elisa",
            "Villa Hernandarias",
            "Villa Mantero",
            "Villa Paranacito",
            "Villa Urquiza",
            "Villaguay"
        ],
        "ISO": "AR-E"
    },
    "Santa Cruz": {
        "Municipios": [
            "Calafate",
            "Caleta Olivia",
            "Comandante Luis Piedrabuena",
            "El Chaltén",
            "Gobernador Gregores",
            "Las Heras",
            "Los Antiguos",
            "Perito Moreno",
            "Pico Truncado",
            "Puerto Deseado",
            "Puerto San Julián",
            "Puerto Santa Cruz",
            "Río Gallegos",
            "Río Turbio",
            "Veintiocho de Noviembre"
        ],
        "ISO": "AR-Z"
    },
    "Río Negro": {
        "Municipios": [
            "Bariloche",
            "Cipolletti",
            "Ing. Jacobacci",
            "El Bolson",
            "Guardia Mitre",
            "Gral. Roca",
            "Luis Beltran",
            "Gral. Conesa",
            "Choele Choel",
            "Lamarque",
            "Coronel Belisle",
            "Darwin",
            "Chimpay",
            "Chichinales",
            "Allen",
            "Cinco Saltos",
            "Campo Grande",
            "Contralmirante Cordero",
            "Mainque",
            "Catriel",
            "Dina Huapi",
            "Gral. Enrique Godoy",
            "Ingeniero Huergo",
            "Villa Regina",
            "Rìo Colorado",
            "El Manso",
            "San Javier",
            "Arroyo Ventana",
            "Laguna Blanca",
            "Pilquiniyeu",
            "Nahuel Niyeu",
            "Sierra Paileman",
            "Peñas Blancas",
            "Paso Flores",
            "Aguada Guzman",
            "Valle Azul",
            "Villa Llanquin",
            "Arroyo los Berros",
            "Rincon de Treneta",
            "Comico",
            "El Cain",
            "Cona Niyeu",
            "Yaminué",
            "El Cuy",
            "Aguada de Guerra",
            "Naupa Huen",
            "Colan Conhué",
            "Mencuen",
            "Ojos de Agua",
            "Clemente Onelli",
            "Pilquiniyeu del Limay",
            "Mamuel Choique",
            "Rio Chico",
            "Viedma",
            "Maquinchao",
            "Sierra Grande",
            "Pilcaniyeu",
            "San Antonio Oeste",
            "Comallo",
            "Los Menucos",
            "Valcheta",
            "Sierra Colorada",
            "Ministro Ramos Mexia",
            "Gral. Fdez. Oro",
            "Pomona",
            "Ñorquinco",
            "Cervantes",
            "Chipauquil",
            "Prahuaniyeu",
            "Aguada Cecilio"
        ],
        "ISO": "AR-R"
    },
    "Chubut": {
        "Municipios": [
            "Rawson",
            "Buen Pasto",
            "Carrenleufú",
            "El Maitén",
            "Puerto Madryn",
            "Cholila",
            "28 de Julio",
            "Río Pico",
            "Alto Río Senguer",
            "Gobernador Costa",
            "El Hoyo",
            "Dolavon",
            "Trelew",
            "José de San Martín",
            "Aldea Beleiro",
            "Cushamen",
            "Dique Florentino Ameghino",
            "Doctor Ricardo Rojas",
            "Corcovado",
            "Puerto Pirámides",
            "Sarmiento",
            "Paso de Indios",
            "Gualjaina",
            "Aldea Epulef",
            "Facundo",
            "Gan Gan",
            "Lago Blanco",
            "Lagunita Salada",
            "Las Plumas",
            "Los Altares",
            "Paso del Sapo",
            "Telsen",
            "Trevelín",
            "Dr. Atilio Oscar Viglione",
            "Comodoro Rivadavia",
            "Lago Puelo",
            "Epuyén",
            "Gaiman",
            "Esquel",
            "Tecka",
            "Rada Tilly",
            "Río Mayo",
            "Camarones",
            "Cerro Centinela",
            "Colan Conhué",
            "Gastre"
        ],
        "ISO": "AR-U"
    },
    "Córdoba": {
        "Municipios": [
            "Cordoba",
            "Villa Gral Belgrano",
            "Ballesteros",
            "Río Bamba",
            "Río Ceballos",
            "Bialet Massé",
            "Jesús María",
            "La Cautiva",
            "La Granja",
            "Colazo",
            "Alcira",
            "Almafuerte",
            "Alpa Corral",
            "Alto Alegre",
            "Achiras",
            "Agua de Oro",
            "Amboy",
            "Alto de los Quebrachos",
            "Anisacate",
            "Arroyo los Patos",
            "Ambul",
            "Arias",
            "Atahona",
            "Ausonia",
            "Avellaneda",
            "Ballesteros Sud",
            "Balnearia",
            "Bañado de Soto",
            "Arroyito",
            "Bell Ville",
            "Berrotarán",
            "Bouwer",
            "Brinkmann",
            "Buchardo",
            "Bengolea",
            "Benjamín Gould",
            "Cavanagh",
            "Cañada de Luque",
            "Cabalango",
            "Villa del Dique",
            "Calmayo",
            "Camilo Aldao",
            "Caminiaga",
            "Canals",
            "Candelaria Sud",
            "Capilla de los Remedios",
            "Capilla del Carmen",
            "Capilla del Sitón",
            "Capitán General B. O'Higgins",
            "Carnerillo",
            "Carrilobo",
            "Cañada de Río Pinto",
            "Cerro Colorado",
            "Chaján",
            "Casa Grande",
            "Charbonier",
            "Chañar Viejo",
            "Chilibroste",
            "Churqui Cañada",
            "Charras",
            "Chuña",
            "Chuña Huasi",
            "Ciénaga del Coro",
            "Colonia Bremen",
            "Colonia Caroya",
            "Colonia las Cuatro Esquinas",
            "Colonia Marina",
            "Colonia Prosperidad",
            "Colonia Italiana",
            "Colonia Iturraspe",
            "Colonia Tirolesa",
            "Colonia las Pichanas",
            "Villa Yacanto",
            "Conlara",
            "Copacabana",
            "Coronel Moldes",
            "Corralito",
            "El Rastreador",
            "Costasacate",
            "Cruz de Caña",
            "Embalse",
            "Colonia San Bartolomé",
            "Cuesta Blanca",
            "Del Campillo",
            "Despeñaderos",
            "Devoto",
            "Diego de Rojas",
            "Dique Chico",
            "El Chacho",
            "El Crispín",
            "El Fortín",
            "Guatimozín",
            "El Manzano",
            "El Rodeo",
            "Esquina",
            "Estación General Paz",
            "Estación Juárez Celman",
            "Estancia de Guadalupe",
            "Estancia Vieja",
            "Etruria",
            "Falda del Carmen",
            "General Cabrera"
        ],
        "ISO": "AR-X"
    },
    "Mendoza": {
        "Municipios": [
            "Mendoza",
            "Maipú",
            "San Rafael",
            "Las Leñas",
            "Valle de Uco",
            "General Alvear",
            "Rivadavia",
            "Tupungato",
            "San Carlos",
            "Tunuyán",
            "Luján de Cuyo",
            "Las Heras",
            "Lavalle",
            "Malargüe",
            "Guaymallén",
            "Capital",
            "Godoy Cruz",
            "Junín",
            "San Martín",
            "Santa Rosa",
            "La Paz"
        ],
        "ISO": "AR-M"
    },
    "La Rioja": {
        "Municipios": [
            "La Rioja",
            "General Ocampo",
            "Chamical",
            "Arauco",
            "General Lamadrid",
            "Vinchina",
            "Capital",
            "Coronel Felipe Varela",
            "Castro Barros",
            "Chilecito",
            "General Ángel Vicente Peñaloza",
            "General Juan Facundo Quiroga",
            "Rosario Vera Peñaloza",
            "General San Martín",
            "Famatina",
            "San Blas de los Sauces",
            "Independencia",
            "General Belgrano",
            "Sanagasta"
        ],
        "ISO": "AR-F"
    },
    "Catamarca": {
        "Municipios": [
            "San Fernando del Valle de Catamarca",
            "Belén",
            "Hualfín",
            "Valle Viejo",
            "Ancasti",
            "Antofagasta de la Sierra",
            "Fiambalá",
            "Tinogasta",
            "Pozo de Piedra",
            "San Fernando",
            "Puerta de San José",
            "Puerta de Corral Quemado",
            "San José",
            "Santa María",
            "Aconquija",
            "Andalgalá",
            "Saujil",
            "Pomán",
            "Mutquín",
            "Santa Rosa",
            "Recreo",
            "Icaño",
            "Paclín",
            "Tapso",
            "Londres",
            "Villa Vil",
            "Los Varela",
            "La Puerta",
            "Las Juntas",
            "El Rodeo",
            "Los Altos",
            "El Alto",
            "Huillapima",
            "Capayán",
            "Fray Mamerto Esquiú",
            "Corral Quemado"
        ],
        "ISO": "AR-K"
    },
    "La Pampa": {
        "Municipios": [
            "La Pampa",
            "Pichi Huinca",
            "Quehué",
            "Abramo",
            "Santa Teresa",
            "General Campos",
            "Trenel",
            "Rancul",
            "Coronel Hilario Lagos",
            "Bernardo Larroude",
            "Ceballos",
            "Intendente Alvear",
            "Miguel Riglos",
            "Toay",
            "Puelén",
            "La Maruja",
            "Arata",
            "Sarah",
            "Ingeniero Luiggi",
            "Eduardo Castex",
            "Monte Nievas",
            "Quemú Quemú",
            "Villa Mirasol",
            "Colonia Barón",
            "Winifreda",
            "Loventué",
            "Santa Isabel",
            "Telén",
            "Ataliva Roca",
            "Bernasconi",
            "Victorica",
            "Metileo",
            "Uriburu",
            "Lonquimay",
            "Luan Toro",
            "Carro Quemado",
            "Perú",
            "Colonia Santa María",
            "Unanue",
            "Jacinto Arauz",
            "Chacharramendi",
            "Tomás Manuel Anchorena",
            "Relmo",
            "Santa Rosa",
            "La Reforma",
            "Limay Mahuida",
            "Gobernador Duval",
            "Falucho",
            "Alta Italia",
            "Anguil",
            "Mauricio Mayer",
            "General San Martín",
            "Casa de Piedra",
            "La Humada",
            "Cuchillo Có",
            "Doblas",
            "Parera",
            "Rucanelo",
            "Caleufú",
            "General Pico",
            "Agustoni",
            "Miguel Cané",
            "Puelches",
            "Algarrobo del Águila",
            "Vértiz",
            "Catriló",
            "Rolón",
            "Adolfo Van Praet",
            "Dorila",
            "Maisonnave",
            "Quetrequén",
            "Veinticinco de Mayo",
            "Macachín",
            "Embajador Martini",
            "Alpachiri",
            "Conhelo",
            "General Acha",
            "Guatraché",
            "Speluzzi",
            "La Adela",
            "Realicó"
        ],
        "ISO": "AR-L"
    },
    "Santiago del Estero": {
        "Municipios": [
            "Santiago del Estero",
            "Añatuya",
            "Bandera",
            "Beltrán",
            "Campo Gallo",
            "Clodomira",
            "Colonia Dora",
            "Fernández",
            "Frías",
            "Ingeniero Forres",
            "La Banda",
            "Loreto",
            "Los Juríes",
            "Los Telares",
            "Monte Quemado",
            "Nueva Esperanza",
            "Pampa de los Guanacos",
            "Pinto",
            "Pozo Hondo",
            "Quimilí",
            "San Pedro de Guasayán",
            "Selva",
            "Sumampa",
            "Suncho Corral",
            "Termas de Río Hondo",
            "Tintina",
            "Villa Atamisqui",
            "Villa Ojo de Agua"
        ],
        "ISO": "AR-G"
    },
    "Corrientes": {
        "Municipios": [
            "Corrientes",
            "Goya",
            "Paso de los Libres",
            "Yataytí Calle",
            "Mercedes",
            "Saladas",
            "Juan Pujol",
            "Pueblo Libertador",
            "Monte Caseros",
            "Colonia Libertad",
            "Parada Pucheta",
            "Sauce",
            "Guaviraví",
            "Tapebicuá",
            "Lavalle",
            "Santa Lucía",
            "Gobernador Martínez",
            "9 de Julio",
            "Felipe Yofré",
            "Chavarría",
            "Estación Torrent",
            "Pedro R. Fernández",
            "Tatacuá",
            "La Cruz",
            "Colonia Carlos Pellegrini",
            "Tabay",
            "Bella Vista",
            "Concepción",
            "Jose Rafael Gomez",
            "Palmar Grande",
            "Mburucuyá",
            "San Miguel",
            "Villa Olivari",
            "Gobernador Ing. Valentín Virasoro",
            "Lomas de Vallejos",
            "Empedrado",
            "San Antonio",
            "Colonia Liebig'S",
            "Riachuelo",
            "Herlitzka",
            "Caá Catí",
            "Loreto",
            "Itá Ibaté",
            "San Carlos",
            "Berón de Astrada",
            "Santa Ana",
            "San Luis del Palmar",
            "Ramada Paso",
            "San Cosme",
            "Paso de la Patria",
            "Mocoretá",
            "San Isidro",
            "Esquina",
            "Curuzú Cuatiá",
            "Bonpland",
            "Yapeyú",
            "Mariano I. Loza",
            "Garruchos",
            "Carolina",
            "Perugorría",
            "Cruz de los Milagros",
            "Alvear",
            "Colonia Pando",
            "San Roque",
            "Itatí",
            "Ituzaingó",
            "San Lorenzo",
            "Colonia Santa Rosa",
            "Santo Tomé"
        ],
        "ISO": "AR-W"
    },
    "Santa Fe": {
        "Municipios": [
            "Santa Fe",
            "Rosario",
            "Pavón",
            "Huanqueros",
            "Arroyo Ceibal",
            "Villa Ana",
            "Aguará Grande",
            "Angeloni",
            "San Mart",
            "Videla",
            "Colonia Dolores",
            "Saladero Mariano Cabal",
            "Helvecia",
            "Colonia Mascias",
            "Pueblo Irigoyen",
            "Coronda",
            "Casalegno",
            "Cañada Rosquín",
            "Colonia Bigand",
            "Pavón Arriba",
            "Melincué",
            "Dos Rosas y la Legua",
            "Colonia Bossi",
            "Las Avispas",
            "Serodino",
            "San Jerónimo Sud",
            "Theobald",
            "Gregoria Pérez de Denis",
            "Barrancas",
            "Monje",
            "Constanza",
            "San Genaro",
            "Sauce Viejo",
            "Santa Margarita",
            "Gato Colorado",
            "San Antonio de Obligado",
            "Tacuarendí",
            "Colonia Durán",
            "Villa Guillermina",
            "Florencia",
            "Bella Italia",
            "Las Palmeras",
            "Venado Tuerto",
            "El Rabón",
            "Las Toscas",
            "Avellaneda",
            "Cañada Ombú",
            "San Bernardo",
            "Fortín Olmos",
            "San Guillermo",
            "Curupaity",
            "Arrufo",
            "La Rubia",
            "Colonia Ana",
            "Villa Trinidad",
            "Palacios",
            "Monigotes",
            "Ambrosetti",
            "La Lucila",
            "Capivara",
            "Colonia la Clara",
            "Montefiore",
            "La Sarita",
            "Tartagal",
            "Malabrigo",
            "Berna",
            "Nicanor Molinas",
            "Juan de Garay",
            "Hersilia",
            "Ceres",
            "La Cabral",
            "San Cristóbal",
            "La Criolla",
            "Vera y Pintado",
            "Intiyaco",
            "La Penca y Caraguatá",
            "Villa Saralegui",
            "Calchaquí",
            "Pozo Borrado",
            "El Arazá",
            "La Gallareta",
            "Toba",
            "Cayastacito",
            "Esther",
            "Pedro Gómez Cello",
            "Hugentobler",
            "Pueblo Marini",
            "Colonia Aldao",
            "Fidela",
            "Vila",
            "Coronel Fraga",
            "San Antonio",
            "Santa Clara de Saguier",
            "Saguier",
            "Villa San José",
            "Rafaela",
            "Estación Clucellas",
            "Angélica",
            "Santa María Centro",
            "Colonia Cello",
            "Josefina",
            "Frontera"
        ],
        "ISO": "AR-S"
    },
    "Tucumán": {
        "Municipios": [
            "San Miguel De Tucuman",
            "Manuel Garcia Fernandez",
            "San Jose de la Cocha",
            "Yanima",
            "El Mollar",
            "Tafi del Valle",
            "La Cocha",
            "El Sacrificio",
            "San Pedro y San Antonio",
            "Gastona y Belicha",
            "Concepcion",
            "Pampa Mayo",
            "Alpachiri y el Molino",
            "Arcadia",
            "Villa Quinteros",
            "Capitan Caceres",
            "Soldado Maldonado",
            "Los Sosa",
            "Simoca",
            "El Timbo",
            "Ancajuli",
            "Los Nogales",
            "El Naranjo y el Sunchal",
            "La Esperanza",
            "El Cadillal",
            "Tapia",
            "Yerba Buena",
            "Las Talitas",
            "Los Puestos",
            "El Puestito",
            "Atahona",
            "El Bracho y el Cevilar",
            "El Naranjito",
            "San Pablo y Villa Nougues",
            "Santa Lucia",
            "Lules",
            "Comuna Villa Belgrano",
            "Delfin Gallo",
            "Alderetes",
            "Graneros",
            "Acheral",
            "Rio Colorado",
            "Amberes",
            "Santa Cruz y la Tuna",
            "Raco",
            "Buena Vista",
            "Rumipunco",
            "Teniente Berdina",
            "Choromoro",
            "Trancas",
            "San Pedro de Colalao",
            "Quilmes y los Sueldos",
            "Los Gomez",
            "Esquina y Mancopa",
            "San Ignacio",
            "Manuela Pedraza",
            "Colombres",
            "Agua Dulce y la Soledad",
            "Gdor. Piedrabuena",
            "San Javier",
            "Juan Bautista Alberdi",
            "Monteagudo",
            "El Polear",
            "Santa Ana",
            "Villa de Chicligasta",
            "Trinidad",
            "Ciudacita",
            "Rio Chico y Nueva Trinidad",
            "Aguilares",
            "Los Sarmiento y la Tipa",
            "Monte Bello",
            "Sargento Moya",
            "Rio Seco",
            "San Andres",
            "Lamadrid",
            "San Felipe y Santa Barbara",
            "Amaicha del Valle",
            "Yerba Buena",
            "Villa Padre Monti",
            "Los Ralos",
            "Taco Ralo",
            "Colalao del Valle",
            "Cevil Redondo",
            "Ranchillos y San Miguel",
            "El Chañar",
            "La Florida y Luisiana",
            "La Ramada y la Cruz",
            "Los Perez",
            "Estacion Araoz y Tacanas",
            "El Mojon",
            "Benjamin Araoz y el Tajamar",
            "Los Pereyras",
            "Garmendia",
            "Las Cejas",
            "Monteros",
            "7 de Abril",
            "Bella Vista",
            "Villa de Leales",
            "Santa Rosa de Leales y L. Blanca",
            "Las Talas"
        ],
        "ISO": "AR-T"
    },
    "Neuquén": {
        "Municipios": [
            "Neuquén",
            "Villa la Angostura",
            "Guañacos",
            "Rincón de los Sauces",
            "Octavio Pico",
            "Buta Ranquil",
            "Barrancas",
            "Añelo",
            "Quili Malal",
            "Las Lajas",
            "Zapala",
            "Mariano Moreno",
            "Senillosa",
            "Junín de los Andes",
            "Aluminé",
            "Villa Traful",
            "Caviahue-Copahue",
            "Plottier",
            "Centenario",
            "Vista Alegre",
            "San Patricio del Chañar",
            "Villa el Chocón",
            "Cutral Có",
            "Plaza Huincul",
            "El Sauce",
            "Picún Leufú",
            "Las Coloradas",
            "Santo Tomás",
            "Los Miches",
            "El Huecú",
            "Loncopué",
            "Bajada del Agrio",
            "Tricao Malal",
            "Villa Curi Leuvú",
            "Huinganco",
            "Varvarco - Invernada Vieja",
            "Los Chihuidos",
            "Ramón Castro",
            "Covunco Abajo",
            "Pilo Lil",
            "Coyuco-Cochico",
            "Los Catutos",
            "Sauzal Bonito",
            "San Martín de los Andes",
            "Villa Pehuenia",
            "Piedra del Águila",
            "Villa del Nahueve",
            "Andacollo",
            "El Cholar",
            "Taquimilán",
            "Chos Malal",
            "Manzano Amargo",
            "Chorriaca",
            "Villa del Puente Picún Leufú",
            "Aguada San Roque",
            "Paso Aguerre",
            "Las Ovejas",
            
        ],
        "ISO": "AR-Q"
    },
    "Salta": {
        "Municipios": [
            "Salta",
            "La Merced",
            "Las Lajitas",
            "Tolar Grande",
            "Cafayate",
            "Cerrillos",
            "Embarcación",
            "Río Piedras",
            "General Güemes",
            "Santa Victoria Este",
            "Campo Quijano",
            "Angastaco",
            "Aguaray",
            "Santa Victoria Oeste",
            "Nazareno",
            "El Bordo",
            "Guachipas",
            "Animaná",
            "Metán",
            "San Lorenzo",
            "Campo Santo",
            "El Tala",
            "La Candelaria",
            "San Ramón de la Nueva Orán",
            "Seclantás",
            "Apolinario Saravia",
            "General Mosconi",
            "Los Toldos",
            "Coronel Moldes",
            "Pichanal",
            "Tartagal",
            "General Ballivián",
            "Joaquín V. González",
            "General Pizarro",
            "Vaqueros",
            "El Quebrachal",
            "Rosario de Lerma",
            "El Carril",
            "Rivadavia Banda Sur",
            "Payogasta",
            "Cachi",
            "Colonia Santa Rosa",
            "El Jardín",
            "San Antonio de los Cobres",
            "Molinos",
            "Rivadavia Banda Norte",
            "Profesor Salvador Mazza",
            "El Potrero",
            "Hipólito Yrigoyen",
            "Iruya",
            "Chicoana",
            "San Carlos",
            "La Poma",
            "Urundel",
            "La Viña",
            "Isla de Cañas",
            "Rosario de la Frontera",
            "La Caldera",
            "El Galpón"
        ],
        "ISO": "AR-A"
    },
    "Chaco": {
        "Municipios": [
            "Resistencia",
            "Isla del Cerrito",
            "Chorotis",
            "Santa Sylvina",
            "Coronel Du Graty",
            "Hermoso Campo",
            "Samuhú",
            "Basail",
            "Puerto Vilelas",
            "Villa Ángela",
            "Fontana",
            "Barranqueras",
            "General Capdevila",
            "Cote Lai",
            "Puerto Tirol",
            "Colonia Popular",
            "San Bernardo",
            "Makallé",
            "Juan José Castelli",
            "Miraflores",
            "Laguna Blanca",
            "Lapachito",
            "La Clotilde",
            "Gancedo",
            "La Escondida",
            "Villa Berthet",
            "La Verde",
            "La Tigra",
            "Las Palmas",
            "General Pinedo",
            "Capitán Solari",
            "Puerto Bermejo",
            "Presidencia de la Plaza",
            "Campo Largo",
            "Corzuela",
            "Puerto Eva Perón",
            "Napenay",
            "La Eduvigis",
            "Presidencia Roque Sáenz Peña",
            "Las Garcitas",
            "Pampa Almirón",
            "Ciervo Petiso",
            "Avia Terai",
            "Laguna Limpia",
            "Gral. San Martengeneral San Martín",
            "Machagai",
            "Concepción del Bermejo",
            "Pampa del Infierno",
            "Presidencia Roca",
            "Pampa del Indio",
            "Los Frentones",
            "Tres Isletas",
            "Villa Río Bermejito",
            "Misión Nueva Pompeya",
            "Fuerte Esperanza",
            "El Sauzalito",
            "Colonia Benitez",
            "Colonias Elisa",
            "Colonias Unidas",
            "General Vedia",
            "Enrique Urien",
            "Charadai",
            "Margarita Belén",
            "La Leonesa",
            "Charata",
            "Las Breñas",
            "Quitilipi",
            "Taco Pozo"
        ],
        "ISO": "AR-H"
    },
    "Formosa": {
        "Municipios": [
            "Formosa",
            "Fortín Lugones",
            "Villa Dos Trece",
            "San Hilario",
            "General Güemes",
            "General Belgrano",
            "Misión Taacaglé",
            "Buena Vista",
            "Laguna Blanca",
            "Laguna Naik Neck",
            "Riacho He-He",
            "Colonia Pastoril",
            "General Mosconi",
            "Ingeniero Guillermo N. Juárez",
            "Los Chiriguanos",
            "Las Lomitas",
            "Pozo del Tigre",
            "Estanislao del Campo",
            "Ibarreta",
            "Comandante Fontana",
            "Palo Santo",
            "Pirané",
            "Gran Guardia",
            "Subteniente Perín",
            "El Colorado",
            "Villa Escolar",
            "San Martín Dos",
            "Misión San Francisco de Laishí",
            "Herradura",
            "General Lucio Victorio Mansilla",
            "Espinillo",
            "Siete Palmas",
            "Clorinda",
            "Portón Negro",
            "Tres Lagunas",
            "Laguna Yema",
            "Mayor Vicente E. Villafañe"
        ],
        "ISO": "AR-P"
    },
    "Jujuy": {
        "Municipios": [
            "San Salvador de Jujuy",
            "Tilcara",
            "Yavi",
            "El Cóndor",
            "Cangrejillos",
            "Abra Pampa",
            "Tres Cruces",
            "Abralaite",
            "Humahuaca",
            "Abdón Castro Tolay",
            "Coranzuli",
            "El Aguilar",
            "Susques",
            "Caspalá",
            "Santa Ana",
            "Huacalera",
            "Catua",
            "Pampichuela",
            "Valle Grande",
            "Yuto",
            "El Talar",
            "Maimará",
            "Calilegua",
            "Vinalito",
            "Libertador General San Martín",
            "Fraile Pintado",
            "Palpalá",
            "Arrayanal",
            "La Esperanza",
            "El Fuerte",
            "Rodeíto",
            "Santa Clara",
            "La Mendieta",
            "San Antonio",
            "Rosario de Río Grande",
            "El Carmen",
            "Perico",
            "Puesto Viejo",
            "Monterrico",
            "Pampa Blanca",
            "Aguas Calientes",
            "Barrios",
            "Rinconada",
            "Santa Catalina",
            "Cieneguillas",
            "La Quiaca",
            "Cusi Cusi",
            "Pumahuasi",
            "Mina Pirquitas",
            "Puesto del Marqués",
            "Hipólito Yrigoyen",
            "Caimancito",
            "Purmamarca",
            "San Francisco",
            "Tumbaya",
            "Volcán",
            "Palma Sola",
            "Yala",
            "El Piquete",
            "San Pedro de Jujuy"
        ],
        "ISO": "AR-Y"
    },
    "Ciudad Autónoma de Buenos Aires": {
        "Municipios": [
            "CABA",
            "Retiro",
            "San Nicolás",
            "Puerto Madero",
            "San Telmo",
            "Montserrat",
            "Constitución",
            "Recoleta",
            "Balvanera",
            "San Cristóbal",
            "La Boca",
            "Barracas",
            "Parque Patricios",
            "Nueva Pompeya",
            "Almagro",
            "Boedo",
            "Caballito",
            "Flores",
            "Parque Chacabuco",
            "Villa Soldati",
            "Villa Riachuelo",
            "Villa Lugano",
            "Liniers",
            "Mataderos",
            "Parque Avellaneda",
            "Villa Real",
            "Monte Castro",
            "Versalles",
            "Floresta",
            "Vélez Sarsfield",
            "Villa Luro",
            "Villa General Mitre",
            "Villa Devoto",
            "Villa del Parque",
            "Villa Santa Rita",
            "Coghlan",
            "Saavedra",
            "Villa Urquiza",
            "Villa Pueyrredón",
            "Núñez",
            "Belgrano",
            "Colegiales",
            "Palermo",
            "Chacarita",
            "Villa Crespo",
            "La Paternal",
            "Villa Ortúzar",
            "Agronomía",
            "Parque Chas"
        ],
        "ISO": "AR-C"
    },
    "Provincia de Buenos Aires": {
        "Municipios": [
            "Pilar",
            "Junín",
            "San Andrés de Giles",
            "Mar del Plata",
            "Saenz Peña",
            "Mar de las Pampas",
            "Lobos",
            "Bahía Blanca",
            "General Alvarado",
            "General Pueyrredón",
            "Mar Chiquita",
            "Pinamar",
            "Magdalena",
            "Vicente López",
            "Pergamino",
            "Rauch",
            "Salliqueló",
            "Coronel Pringles",
            "Saladillo",
            "Las Flores",
            "Rojas",
            "Escobar",
            "Bolívar",
            "José C. Paz",
            "Maipú",
            "La Matanza",
            "San Antonio de Areco",
            "Moreno",
            "General Paz",
            "General Guido",
            "General Juan Madariaga",
            "Tandil",
            "Coronel Suárez",
            "Adolfo Gonzales Chaves",
            "Villa Gesell",
            "General Lavalle",
            "La Costa",
            "Berazategui",
            "Tornquist",
            "Tigre",
            "Adolfo Alsina",
            "Pellegrini",
            "Villarino",
            "Puán",
            "General Villegas",
            "Castelli",
            "Almirante Brown",
            "La Plata",
            "Presidente Perón",
            "Brandsen",
            "Carlos Casares",
            "Carlos Tejedor",
            "9 de Julio",
            "Pehuajó",
            "Trenque Lauquen",
            "Roque Pérez",
            "Olavarría",
            "Arrecifes",
            "Capitán Sarmiento",
            "Carmen de Areco",
            "Salto",
            "Merlo",
            "Esteban Echeverría",
            "Exaltación de la Cruz",
            "San Miguel",
            "Luján",
            "Chacabuco",
            "Mercedes",
            "Hurlingham",
            "General Rodríguez",
            "Morón",
            "Lincoln",
            "Ituzaingó",
            "Suipacha",
            "Marcos Paz",
            "Tres de Febrero",
            "Chivilcoy",
            "Alberti",
            "Bragado",
            "Lanús",
            "General las Heras",
            "Lomas de Zamora",
            "Florencio Varela",
            "Quilmes",
            "Pila",
            "Navarro",
            "Cañuelas",
            "San Vicente",
            "General la Madrid",
            "Benito Juárez",
            "Balcarce",
            "Azul",
            "Guaminí",
            "Tordillo",
            "Avellaneda",
            "San Isidro",
            "Patagones",
            "Coronel de Marina Leonardo Rosales",
            "Colón",
            "Saavedra",
            "Monte Hermoso",
            "Lobería",
            "Berisso",
            "San Fernando",
            "Zárate"
        ],
        "ISO": "AR-B"
    },
    "Tierra del Fuego": {
        "Municipios": [
            "Ushuaia",
            "Río Grande",
            "Tolhuin"
        ],
        "ISO": "AR-V"
    }
}

rows = []

for state, state_data in data.items():
    iso = state_data["ISO"]
    municipalities = state_data["Municipios"]
    for idx, city_name in enumerate(municipalities, start=1):
        rows.append({"city_id": idx, "state_id": iso, "city_name": city_name})

df = pd.DataFrame(rows)

db_params = {
    "dbname": "",
    "user": "",
    "password": "",
    "host": "localhost",
    "port": "5432"
}

conn = psycopg2.connect(**db_params)

cur = conn.cursor()

existing_city_ids = pd.read_sql("SELECT city_id, state_id FROM cities", conn)
df_to_insert = df[~df.set_index(['city_id', 'state_id']).index.isin(existing_city_ids.set_index(['city_id', 'state_id']).index)]

for _, row in df_to_insert.iterrows():
    cur.execute("INSERT INTO cities (city_id, state_id, city_name) VALUES (%s, %s, %s) ON CONFLICT DO NOTHING",
                (row["city_id"], row["state_id"], row["city_name"]))

conn.commit()
cur.close()
conn.close()

# # Filtrar los datos para insertar solo las filas que no existen
# existing_city_names = pd.read_sql("SELECT city_name FROM cities", conn)["city_name"]
# df_to_insert = df[~df["city_name"].isin(existing_city_names)]

# engine = create_engine(f'postgresql+psycopg2://{db_params["user"]}:{db_params["password"]}@{db_params["host"]}:{db_params["port"]}/{db_params["dbname"]}')

# df_to_insert.to_sql('cities', engine, if_exists='append', index=False)

# conn.close()

print("listo :)")